/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;

@CDIView("Articulos")
public class ListarArticulos extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnGuardarArticulo;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField txtPrecio;
	@AutoGenerated
	private TextField txtKgs;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private TextField txtCodigo;
	@AutoGenerated
	private Table table_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ListarArticulos() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("483px");
		table_1.setHeight("-1px");
		mainLayout.addComponent(table_1, "top:17.0px;left:17.0px;");
		
		// txtCodigo
		txtCodigo = new TextField();
		txtCodigo.setImmediate(false);
		txtCodigo.setWidth("-1px");
		txtCodigo.setHeight("-1px");
		mainLayout.addComponent(txtCodigo, "top:382.0px;left:80.0px;");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setImmediate(false);
		txtNombre.setWidth("-1px");
		txtNombre.setHeight("-1px");
		mainLayout.addComponent(txtNombre, "top:416.0px;left:80.0px;");
		
		// txtKgs
		txtKgs = new TextField();
		txtKgs.setImmediate(false);
		txtKgs.setWidth("-1px");
		txtKgs.setHeight("-1px");
		mainLayout.addComponent(txtKgs, "top:460.0px;left:80.0px;");
		
		// txtPrecio
		txtPrecio = new TextField();
		txtPrecio.setImmediate(false);
		txtPrecio.setWidth("-1px");
		txtPrecio.setHeight("-1px");
		mainLayout.addComponent(txtPrecio, "top:500.0px;left:80.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Nombre");
		mainLayout.addComponent(label_2, "top:422.0px;left:17.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Peso");
		mainLayout.addComponent(label_3, "top:462.0px;left:20.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Precio");
		mainLayout.addComponent(label_4, "top:502.0px;left:17.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Codigo");
		mainLayout.addComponent(label_1, "top:382.0px;left:17.0px;");
		
		// btnGuardarArticulo
		btnGuardarArticulo = new Button();
		btnGuardarArticulo.setCaption("Guardar");
		btnGuardarArticulo.setImmediate(false);
		btnGuardarArticulo.setWidth("-1px");
		btnGuardarArticulo.setHeight("-1px");
		mainLayout
				.addComponent(btnGuardarArticulo, "top:534.0px;left:140.0px;");
		
		return mainLayout;
	}

}
